[package]
name = "Capping2025"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.6", features = ["macros", "multipart"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["full"] }
pgvector = { version = "0.3.4", features = ["sqlx"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.31", features = ["serde"] }
tower-http = { version = "0.4", features = ["cors"] }
http = "0.2"
dotenv = "0.15.0"
serde_json = "1.0"