[package]
name = "Capping2025"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.5"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.47.1", features = [ "full" ] }
pgvector = { version = "0.4.1", features = ["sqlx"] }
serde = { version = "1.0.228", features = [ "derive" ] }
chrono = { version = "0.4.42", features = [ "serde" ] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.20"