[package]
name = "Capping2025"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["full"] }
pgvector = { version = "0.3.4", features = ["sqlx"] }
