[run]
run-types = ["Benchmarks", "Examples", "Doctests", "Tests"]
all-features = true
force-clean = false
skip-clean = true
locked = true

[report]
output-dir = "tmp"
out = ["Stdout", "Html"]
fail-under = 80