name: User Story
description: Create a user story.
title: "[STORY] "
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
    validations:
      required: true
  - type: textarea
    id: dev-notes
    attributes:
      label: Developer Notes
    validations:
      required: true