name: Epic
description: Create an epic.
title: "[EPIC] <Epic title>"
labels: ["epic"]
projects: ["CFdefense/2"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature or requirement from a user perspective.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what must be true for this epic to be considered complete.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true
  - type: textarea
    id: dev-notes
    attributes:
      label: Developer Notes
      description: (Optional)Additional notes and considerations for implementation
    validations:
      required: false
  - type: textarea
    id: stories
    attributes:
      label: Stories
      description: Add related story issue numbers below. This will be auto-updated as stories are added and link to this epic.
      placeholder: Stories to be added...
    validations:
      required: false