name: Story
description: Create a user story.
title: "[STORY] <Story title>"
labels: ["story"]
projects: ["CFdefense/2"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature or requirement from a user perspective.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what must be true for this story to be considered complete.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true
  - type: textarea
    id: dev-notes
    attributes:
      label: Developer Notes
      description: (Optional) Additional notes and considerations for implementation
    validations:
      required: false
  - type: input
    id: epic_number
    attributes:
      label: Parent Epic Number
      description: Enter the number of the Epic this story belongs to (e.g., #100)
      placeholder: #100
    validations:
      required: true