use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use chrono::NaiveDateTime;

/// Row model for `message` table
#[derive(Serialize, Deserialize, FromRow)]
pub struct MessageRow {
	/// Primary key
	pub id: i32,
	/// Chat session this message belongs to
	pub chat_session_id: i32,
	/// Possible itinerary associated with this message
	pub itinerary_id: Option<i32>,
	/// Whether this message was sent by the user or generated by the LLM
	pub is_user: bool,
	/// UTC timestamp this message was sent (%Y-%m-%d %H:%M:%S)
	pub timestamp: NaiveDateTime,
	/// Content of the message
	pub text: String
}